### PR TITLE
Add TNS external search for sources

### LINKED ISSUE #498: Include TNS as a name resolver
Add the Transient Name Server as a name resolver (in addition to SIMBAD etc) for the cone search

### PR DESCRIPTION
**Pull request by marxide**
This PR adds cone search results from the [Transient Name Server](https://www.wis-tns.org) to the "External Search Results" table on the source detail page. These results contain cone search results from SIMBAD, NED, and now TNS.

As part of this, the external search functions have been refactored to their own module with the intent of simplifying the implementation of other external providers in the future.

Added documentation for the TNS resolver as it requires an API key.

Added tests for all external search providers using a well known transient source (SN 2018cow).

Closes #498.

### CODE REVIEW

**Comment by marxide** [comment]
This can be a bit hard to test visually since you need to find a VAST source that's also in TNS. I found one at 13h21m15.64s -08d08m28.45s that appears in field VAST_1326-06A.

Example VAST source with TNS result

**Comment by ajstewart** [comment]
While this looks great, I wondered if the original aim of #498 was to have TNS available as an option in the cone search name resolver on the query page?

**Review by ajstewart — COMMENTED** [review]
But just to add this is good to go and I would be happy to approve, depending on the cone search question.

**Comment by marxide** [comment]
> While this looks great, I wondered if the original aim of #498 was to have TNS available as an option in the cone search name resolver on the query page?

@dlakaplan?

I interpreted it as a feature for the external cone search rather than the name resolver since I think that's more useful. When we had a list of candidates from VAST-P1, I was pasting the coordinates of each to check for TNS matches which gets tedious with many sources.

**Comment by marxide** [comment]
Merging for now. If we want a TNS name resolver on the source query page, we can open another issue for that.

**Pull request merged**
