### PR TITLE
compute ideal source coverage with astropy xmatch

### LINKED ISSUE #554: High memory usage during sky region ideal coverage
When attempting to perform a full-scale run, I encountered OOM errors during the sky region ideal coverage stage in `vast_pipeline.pipeline.utils.get_src_skyregion_merged_df`.

The current implementation creates a Cartesian product of all sources and sky regions and filters the results by a separation threshold from there. For a full-scale VAST-P1 run with almost 1 million sources and almost 1,000 sky regions, this approach requires a lot of memory.

### PR DESCRIPTION
**Pull request by marxide**
Previous implementation required the Cartesian product of every source and sky region be held in memory. Fixes #554.

### CODE REVIEW

**Comment by marxide** [comment]
You can ignore the failing check, it's from the linter and for existing code not touched by this PR. I will make a PR to fix the basic linter errors soon, see #556.

**Review by ajstewart — APPROVED** [review]
This looks like it's ready to go to me!

You've just replaced that part with an astropy crossmatch search around sky, right? Definitely a leaner way to go, thanks. 

On a side note, from memory, I had speed issues when performing separation calculations using astropy in conjunction with a pandas.apply() and/or vectorising things - that's pretty much the only reason that `on_sky_sep` function exists.

**Comment by marxide** [comment]
> You've just replaced that part with an astropy crossmatch search around sky, right? Definitely a leaner way to go, thanks.

Yes. Instead of making a DataFrame of each source and sky region combination with their separations then filtering by the separation, it does the same with the astropy search around sky function. The separation threshold needs to be different per sky region, so I use the maximum first, then filter again properly later.

> On a side note, from memory, I had speed issues when performing separation calculations using astropy in conjunction with a pandas.apply() and/or vectorising things - that's pretty much the only reason that `on_sky_sep` function exists.

I didn't test if this is any faster or slower. It might be slower, but I think sacrificing speed in return for avoiding OOM errors is preferable!

**Comment by ajstewart** [comment]
> > On a side note, from memory, I had speed issues when performing separation calculations using astropy in conjunction with a pandas.apply() and/or vectorising things - that's pretty much the only reason that `on_sky_sep` function exists.
> 
> I didn't test if this is any faster or slower. It might be slower, but I think sacrificing speed in return for avoiding OOM errors is preferable!

For sure! Just wanted to give context on why that function is there in the first place.

**Pull request merged**
